### PR TITLE
day_02 & day_03

### PR DESCRIPTION
**Pull request by lynly**
How difficult did you find this (out of 10)? day_02 exercises - 8, MTA - 9, OMDB - 8 
Was there anything that you struggled with? Loops - each do? I don't think i have a full grasps of it in ruby yet. MTA struggled with this quite a lot. OMDB couldn't figure out the bonus rounds.
Is there anything that you'd like some further information on? from day_02 hashes - # How would you return an array of the favorite numbers common to all users? 
Roughly how long did it take? 3-4 hrs daily

### CODE REVIEW

**Comment by Phoboes** [comment]
`How difficult did you find this (out of 10)? day_02 exercises - 8, MTA - 9, OMDB - 8Was there anything that you struggled with? Loops - each do? I don't think i have a full grasps of it in ruby yet. `
____
## Loops, blocks and `do`ing
____

In ruby loops and conditionals usually come in 2 syntaxes, blocks(`{}`) and `do`.

They work very slightly differently, but ordinarily you shouldn't have to worry too much about them.

To show how they work, I'm going to write out a quick ruby file:

```rb
array = ["one", "two", "three", "four", "five", "six", "seven"]

array.each { p array  }
```

If I run this, what it says is, "For each element in my chosen data, **do** something". In this case, it's going to print out the whole array 7 times ( once for each item in the array).

Because it's not something like a for loop, we don't get access to things like `i` to mess around with. How do I go about actually getting in to the piece of the array I'm on?

To do this, we can nominate a variable name for each step of the array.

```rb
array.each { | index | p index  }


=> 
  "one"
  "two"
  "three"
  "four"
  "five"
  "six"
  "seven"
```

Now we've said, "For every item in my data, step through, but as you do, give me a variable called index. I want that index to be whatever item you are currently on". 

To see this in a  more familiar context, if I wrote this in Javascript:

```js
for( var i = 0; i < array.length; i++ ){
  console.log( i )
}
```

So, there's the basics of our block version. That's alright for a one liner, the block is short and succinct, but if we are doing more, it starts to get really messy and unreadable. Here's where `each do` comes in.

To change our code:

```rb
array.each do | index | 
  p index  
end
```

We're doing exactly the same thing, but breaking it out over multiple lines. This also means we now need an `end` (to close the `do` word). Any time you start something with `do`, you will need to `end` it. You can think of these almost as brackets on a function in js. They tell it when to start/stop a certain block of logic.

Now that we've broken our code up over multiple lines, we can do more while keeping it readable.
If it's a one liner, we'll usually use blocks `{}, otherwise we use `do`.

Arrays are easy to navigate, what about a hash? `hash[0]` is never going to be much use to me. Lets change our code a bit:

```rb
hash = {
  "one" => 1,
  "two" => 2,
  "three" => 3,
  "four" => 4,
  "five" => 5,
  "six" => 6,
  "seven" => 7
}


hash.each do | item | 
  p item  
end

=>
  ["one", 1]
  ["two", 2]
  ["three", 3]
  ["four", 4]
  ["five", 5]
  ["six", 6]
  ["seven", 7]

```

Our code is nearly the same, but now we're just getting arrays back. That's... not very helpful.
Why? Because we're dealing with a hash. It has a `key` and a `value`. When we log out item, we're just saying, "Give me one of whatever is in each data point for this hash".

Fortunately, we tell our loop to dig a little deeper by adding another variable to evaluate in our loop:

```rb
hash.each do | key, value | 
  p "The key is: #{ key }, the value is: #{ value }"
  p "-----"  
end


=>

  "The key is: one, the value is: 1"
  "-----"
  "The key is: two, the value is: 2"
  "-----"
  "The key is: three, the value is: 3"
  "-----"
  "The key is: four, the value is: 4"
  "-----"
  "The key is: five, the value is: 5"
  "-----"
  "The key is: six, the value is: 6"
  "-----"
  "The key is: seven, the value is: 7"
```

There you have it. 

Again, my best advice for working out exactly what data you are dealing with would be just to throw pry in the mix and start calling things in the terminal, but I hope that clears things up a tiny bit for you.

**Comment by Phoboes** [comment]
`Is there anything that you'd like some further information on? from day_02 hashes - # How would you return an array of the favorite numbers common to all users?`

____

You can find my answers to those exercises [here](https://github.com/ga-wolf/wdi-21/tree/master/05-ruby/ruby_class_exercises/hashes), for this one in particular:

```rb
# How would you return an array of the favorite numbers common to all users?

 arr = []

users.keys.each { | key, value | arr.push users[key][:favorite_numbers]  }
```

And the follow on that strips all the duplicates and sorts them:

```
# How would you return an array containing all users' favorite numbers, sorted, and excluding duplicates?

# Chained commands - flatten the array into one big single array, get all unique values and sort them.
arr.flatten.uniq.sort
```

To break down the logic, I want to:

- Store all the numbers somewhere - a new `array` is ideal for this.
- Go through every user - an `each` loop
- Once I have a user, I want to dig in to that user and get their numbers, then `push` them to my array.

At the end, this will give me an array that has all the arrays of their numbers.

Next:

- I already have my data, now I want to tidy it.
- Firstly, I don't want an array of arrays. I want numbers. I can call [flatten](https://apidock.com/ruby/Array/flatten) to squish them into one array.
- I now have my array of numbers, I just want the unique ([uniq](https://apidock.com/ruby/Array/uniq)) ones. 
- Now I have an array with all the unique numbers. Now I just need to [sort](https://apidock.com/ruby/Array/sort) them.

This is a new language, and the syntaxes can be frustrating to learn, it takes time and practice to know what sorts of tricky methods you can expect to find in programming languages. It gets easier with time.

**Comment by Phoboes** [comment]
Jack mentioned you were after the basic pseudocode approach for tic tac toe, so I'll take a stab at that for you, too.

Ideally, I want to break the project down into the smallest, most basic steps I can.

1. Draw my game

2. Interact with my game

3. begin evaluating those interactions.

____

#### Drawing the game:

1. I want a box on the screen.

```html
 <div class="container"></div>
```
```css
.container {
  margin: auto;
  border: 1px solid black;
  width: 80vh;
  height: 80vh;
  margin-top: 10vh;
  font-size: 0;
}
```

2. I want my cells inside that box.

```html
  <div class="container">
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
  </div>
```
```css
.container {
  margin: auto;
  /*border: 1px solid black;*/
  width: 80vh;
  height: 80vh;
  margin-top: 10vh;
  font-size: 0;
}

.cell {
  width: 33.3%;
  height: 33.3%;
  display: inline-block;
  border: 1px solid black;
  box-sizing: border-box;
}
```

There is my first hurdle down. Next, I want interaction.

____

#### Interacting with my game:

1. I want to be able to click a box and have something happen. In this case, the box turns red.

To do this, I'm going to use jQuery to listen for a click on any cell.

```js
$(document).ready(function(){

  $('.cell').click( function(){
    $( this ).css("background-color", "red");
  });
  
}); // end docReady
```

clicky

____

#### Evaluating interactions

Basic stuff done, this is where logic starts coming in to it - my approach is this:

1. I need to be able to alternate turns. If it's my turn, play a red box, if it's not, play a blue one.
    * Make a turn counter

2. I need to store my moves somewhere
   * Make an array or something to store moves

3. Make sure that when I click an element, the move is stored in the right place in my moves

4. Make sure that I can't play in the same spot twice.

____

My first 3 steps get me here:

```js
var board = [
  [   ], [   ], [   ],
  [   ], [   ], [   ],
  [   ], [   ], [   ]

turn = 1;

  $('.cell').click( function(){
    // var cellIndex = $(this).index();

    if( turn % 2 === 0 ){
      $( this ).css("background-color", "blue");
    } else {
      $( this ).css("background-color", "red");
    }
  turn += 1;
  });
```

alternate

3 and 4 are a little trickier.

3: get the index. Fortunately, jQuery has an [index](https://api.jquery.com/index/) function, which will tell me what number a given element is.

That means it's relatively easy for me to make my array match my game board, I can pass that index directly to the array that mimics my board.

4: Prevent duplicate moves.

I now have my array, which mimics my board, I can just say, "If this index has a value, don't play the move."

```js
  $('.cell').click( function(){
    var cellIndex = $(this).index();

    if( board[ cellIndex ].length === 0 ){
      if( turn % 2 === 0 ){
        $( this ).css("background-color", "blue");
        board[ cellIndex ] = "p2";
      } else {
        $( this ).css("background-color", "red");
        board[ cellIndex ] = "p1";
      }
    }

  turn += 1;
  });
```
____

#### The rest:

That's the basics of tic tac toe done.
From here:

1.  Win conditions
  * Check my array for combinations that equal a win. For instance:
```js
  ["p1"], ["p1"], ["p1"],
  [       ], [       ], [       ],
  [       ], [       ], [       ]
```
should be considered a win.

2. Check draw conditions.
  * If my turn count is 9, and I haven't won -- It must be a draw.

3. Reset my board. -- things to reset:
  * Turns
  * Board
  * Array

___

I hope that helps a little.

**Comment by Phoboes** [comment]
# Your tic tac toe
____

Sorry, I realised I haven't actually reviewed your tic tac toe.

I don't actually have much feedback in the way of your code, you've done a really nice job.

The one thing I would suggest:

```js
////// CONSIDER LATER: turn to a loop for less code //////
$("div.box1").on('click', function (event){
  if (currentPlayer === xPlay) {
    $( "div.box1 img.selectedImage" ).attr('src', xImage); // show src of xImage when div.box1 is clicked to test later in function
    $( "div.box1 img.selectedImage" ).show();
    currentPlayer = oPlay;
    $( "button#x-player" ).removeClass("active");
    $( "button#o-player" ).addClass("active");
    $( this ).off( event );
  } else if (currentPlayer === oPlay) {
    $( "div.box1 img.selectedImage" ).attr('src', oImage);
    $( "div.box1 img.selectedImage" ).show();
    currentPlayer = xPlay;
    $( "button#o-player" ).removeClass("active");
    $( "button#x-player" ).addClass("active");
    $( this ).off( event );
  }
  wincombo(); /// run function to test winning combinations
});
```
You are repeating this pattern for every single cell on your grid, it means you are repeating your code a lot. Something important to remember is that elements can have multiple classes, instead of:

```html
    <div class="row1">
      <div class="box1">
          <img class="selectedImage" src="#1" style="display: none">
      </div>
      <div class="box2">
        <img class="selectedImage" src="#2" style="display: none">
      </div>
      <div class="box3">
        <img class="selectedImage" src="#3" style="display: none">
      </div>
```
I would suggest this:

```html
    <div class="row row1">
      <div class="box box1">
```
And then this:

```js
$("div").on('click', function (event){
```

Now you have chained the click to **any** cell. From there, you just need to work with the `this` keyword, and you get:

```js
$(".box").on('click', function (event){
  if (currentPlayer === xPlay) {
    $( this ).find( "img.selectedImage" ).attr('src', xImage); // show src of xImage whenthis l.find(  is clicked to test )ater in function
    $( this ).find( "img.selectedImage" ).show();
    currentPlayer = oPlay;
    $( "button#x-player" ).removeClass("active");
    $( "button#o-player" ).addClass("active");
    $( this ).off( event );
  } else if (currentPlayer === oPlay) {
    $( this ).find( "img.selectedImage" ).attr('src', oImage);
    $( this ).find( "img.selectedImage" ).show();
    currentPlayer = xPlay;
    $( "button#o-player" ).removeClass("active");
    $( "button#x-player" ).addClass("active");
    $( this ).off( event );
  }
  wincombo(); /// run function to test winning combinations
});
```

With that, you can delete every other click handler. This will do all of it.

Shared classes also mean things like:

```css
.box1, .box2, .box3, .box4, .box5, .box6, .box7, .box8, .box9 
```

become `box`.

____

That's really it, you've actually done a really neat job here.

**Comment by lynly** [comment]
Hey kane,

Thanks for this and all your help, especially in the early am of last night, technically this morning hahaha  It's been so helpful even though I seem lost when u explain things it does make sense! The lost look is just the normal state of my face lol yeah tic-tac-toe is something I want to revisit cuz I was annoyed I couldn't figure out how to make it non repetitive! You has also sent through something earlier on this as well which i will also refer to!

Hey just wondering with your gitbook notes do we still have access to those files after the course? Or is it something I download? I don't think I fully understand the powers of git yet aside from the backups

Anyways thanks for being awesome and have a great weekend

Cheers,
Lynda
________________________________

**Comment by Phoboes** [comment]
It's fine, I'm just glad to help.

The notes and homework are always available (along with everyone else's).

**Comment by lynly** [comment]
Excellent, it will be great to refer back to!

Also with my project 01 every time I try to do the user authentication part and then seed the data it errors saying something about a password needing to be required ... it has something to do with the has_secure_key in my doctor controller as soon as I remove that it seeds fine.

Is this because in my seed data I never signed up with user password and confirmation for it to generate the password digest? Cuz I currently have 3 Drs in my seed without a password digest? If I remove the three and sign up with their details will this allow user authentication to work?

Cheer,
Lynda
________________________________

**Pull request merged**
